export default {
    TIMESTEP: 1 / 60,
    MAX_FRAME_SKIP: 16,
    VAULT_SIZE: 48,
    GRAVITY_CONSTANT: 120,
    SPRING_K: 0.40,
    DAMPING: 1.0,
    SUBSTEPS: 8,
    PARTICLE_R: 9,
    BREAK_MULT: 2.8,
    COLLISION_R_BASE_MULT: 1.15,
    MAX_BODIES: 8,
    MAX_LOOSE_PARTICLES: 400
};